org: gelca
app: trial-1
service: pig-latin
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: random-sentence
          method: get
      - http:
          path: translate
          method: post
plugins:
  - serverless-offline
