service: sls-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  randomSentence:
    handler: handlers/randomSentence.generate
    events:
      - http:
          path: random-sentence
          method: get
          cors: true
  translate:
    handler: handlers/translate.generate
    events:
      - http:
          path: translate
          method: post
          cors: true

plugins:
  - serverless-offline
