service: sls-offline

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DB_HOST: ${.env:DB_HOST}
    DB_USER: ${.env:DB_USER}
    DB_PASSWORD: ${.env:DB_PASSWORD}
    DB_NAME: ${.env:DB_NAME}
    DB_PORT: ${.env:DB_PORT}

functions:
  randomSentence:
    handler: handlers/randomSentence.generate
    events:
      - http:
          path: random-sentence
          method: get
          cors: true
  translate:
    handler: handlers/translate.generate
    events:
      - http:
          path: translate
          method: post
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
